# Generated by Django 4.2.3 on 2023-11-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up_page', '0002_alter_sign_up_datas_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up_datas',
            name='email',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='sign_up_datas',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
