# Generated by Django 4.2.3 on 2023-11-07 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up_page', '0003_alter_sign_up_datas_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign_up_datas',
            old_name='email',
            new_name='User',
        ),
    ]
