# Generated by Django 4.2.3 on 2023-11-07 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up_page', '0004_rename_email_sign_up_datas_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign_up_datas',
            old_name='User',
            new_name='email',
        ),
    ]
