# Generated by Django 4.2.3 on 2023-09-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_in_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('un', models.CharField(max_length=23)),
                ('IN', models.CharField(max_length=23)),
            ],
        ),
        migrations.AlterField(
            model_name='log_in_datas',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='log_in_datas',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
