# Generated by Django 4.2.6 on 2023-10-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task_add',
            new_name='Task_addition',
        ),
    ]
