# Generated by Django 4.2.6 on 2023-10-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0002_rename_task_add_task_addition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_addition',
            name='Task_description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='task_addition',
            name='Task_heading',
            field=models.CharField(default='', max_length=50),
        ),
    ]
