# Generated by Django 4.2.6 on 2023-10-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0003_alter_task_addition_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_addition',
            name='Task_description',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='task_addition',
            name='Task_heading',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
