# Generated by Django 4.2.6 on 2023-10-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0004_alter_task_addition_task_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task_addition',
            new_name='Task_add',
        ),
    ]
