# Generated by Django 4.2.6 on 2023-10-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_page', '0005_rename_task_addition_task_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_add',
            name='Email',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task_add',
            name='Id',
            field=models.CharField(default='', max_length=5, null=True),
        ),
    ]
